name: Image optimization

on:
  push:
    paths:
      - 'assets/images/**'

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install webp tools
        run: sudo apt-get update && sudo apt-get install -y webp

      - name: Convert PNGs to WebP
        run: |
          set -e
          cd assets/images
          for f in *.png; do
            [ -f "$f" ] || continue
            out="${f%.png}.webp"
            if [ ! -f "$out" ]; then
              cwebp -q 80 "$f" -o "$out" || true
            fi
          done

      - name: Commit optimized images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add --all assets/images/*.webp || true
          if ! git diff-index --quiet HEAD --; then
            git commit -m "ci(images): add webp-optimized versions of images"
            git push
          else
            echo "No optimized images to commit"
          fi
